window.LP_TEMPLATES = [
  {
    key: 'workshop-icebreaker',
    category: 'Workshop & Moderation',
    name: 'Workshop Einstieg',
    desc: 'Eisbrecher, Erwartungen und Abschluss-Feedback.',
    duration: '20–40 Min.',
    group: '8–40',
    slides: [
      { slide_type: 'content', content: { title: 'Willkommen', body: 'Schön, dass ihr dabei seid!' }, settings: {} },
      { slide_type: 'wordcloud', content: { title: 'Eisbrecher', prompt: 'Ein Wort, das deine Stimmung heute beschreibt' }, settings: { anonymous: true } },
      { slide_type: 'scale', content: { title: 'Erwartungen', prompt: 'Wie klar sind deine Erwartungen an heute?', min: 1, max: 10, minLabel: 'unklar', maxLabel: 'sehr klar' }, settings: {} },
      { slide_type: 'open', content: { title: 'Abschluss', prompt: 'Was nimmst du mit?' }, settings: { anonymous: true } },
    ],
  },
  {
    key: 'education-quiz',
    category: 'Bildung & Unterricht',
    name: 'Unterricht Quiz',
    desc: 'Vorwissen, Verständnis-Check und Quiz.',
    duration: '30–45 Min.',
    group: '10–120',
    slides: [
      { slide_type: 'mc_single', content: { title: 'Vorwissen', prompt: 'Wie vertraut bist du mit dem Thema?', options: [{ id: 'a', text: 'Neu' }, { id: 'b', text: 'Grundlagen' }, { id: 'c', text: 'Fortgeschritten' }] }, settings: { anonymous: true } },
      { slide_type: 'yesno', content: { title: 'Verständnis-Check', prompt: 'Bist du bereit für das Quiz?' }, settings: {} },
      { slide_type: 'quiz', content: { title: 'Quiz Frage 1', prompt: 'Was ist korrekt?', options: [{ id: 'a', text: 'Antwort A', correct: false }, { id: 'b', text: 'Antwort B', correct: true }, { id: 'c', text: 'Antwort C', correct: false }] }, settings: { timeLimitSec: 20 } },
      { slide_type: 'scale', content: { title: 'Reflexion', prompt: 'Wie sicher fühlst du dich jetzt?', min: 1, max: 5 }, settings: { anonymous: true } },
    ],
  },
  {
    key: 'meeting-pulse',
    category: 'Unternehmens-Meetings',
    name: 'Team Pulscheck',
    desc: 'Stimmungsbild und Priorisierung.',
    duration: '15–25 Min.',
    group: '5–30',
    slides: [
      { slide_type: 'reaction', content: { title: 'Stimmung', prompt: 'Wie geht es dir heute?' }, settings: { anonymous: true } },
      { slide_type: 'mc_multi', content: { title: 'Prioritäten', prompt: 'Welche Themen sind wichtig? (max. 3)', options: [{ id: 'a', text: 'Kunden' }, { id: 'b', text: 'Produkt' }, { id: 'c', text: 'Team' }, { id: 'd', text: 'Prozesse' }], maxSelections: 3 }, settings: {} },
      { slide_type: 'open', content: { title: 'Offene Punkte', prompt: 'Was blockiert uns gerade?' }, settings: { moderation: true } },
    ],
  },
  {
    key: 'retro',
    category: 'Unternehmens-Meetings',
    name: 'Retrospektive',
    desc: 'Gut · Schlecht · Mitnehmen.',
    duration: '30–60 Min.',
    group: '4–15',
    slides: [
      { slide_type: 'brainstorm', content: { title: 'Gut gelaufen', prompt: 'Was lief gut?' }, settings: { anonymous: true } },
      { slide_type: 'brainstorm', content: { title: 'Schlecht gelaufen', prompt: 'Was lief schlecht?' }, settings: { anonymous: true } },
      { slide_type: 'brainstorm', content: { title: 'Mitnehmen', prompt: 'Was nehmen wir uns vor?' }, settings: {} },
    ],
  },
  {
    key: 'townhall-qa',
    category: 'Konferenzen & Events',
    name: 'Town Hall Q&A',
    desc: 'Publikumsfragen mit Upvotes.',
    duration: '20–45 Min.',
    group: '20–500',
    slides: [
      { slide_type: 'content', content: { title: 'Town Hall', body: 'Stellt eure Fragen – wir stimmen ab.' }, settings: {} },
      { slide_type: 'qa', content: { title: 'Fragen an das Team', prompt: 'Was möchtest du fragen?' }, settings: { anonymous: true } },
    ],
  },
  {
    key: 'hr-onboarding',
    category: 'HR & Team-Building',
    name: 'Onboarding Pulse',
    desc: 'Anonymes Feedback für neue Teams.',
    duration: '10–20 Min.',
    group: '5–25',
    slides: [
      { slide_type: 'scale', content: { title: 'Onboarding', prompt: 'Wie gut fühlst du dich bisher integriert?', min: 1, max: 10 }, settings: { anonymous: true } },
      { slide_type: 'wordcloud', content: { title: 'Erste Eindrücke', prompt: 'Ein Wort zu deinem Start' }, settings: { anonymous: true } },
    ],
  },
  {
    key: 'product-prioritize',
    category: 'Marktforschung & Produkt',
    name: 'Feature-Priorisierung',
    desc: '100-Punkte-Verteilung auf Features.',
    duration: '15–30 Min.',
    group: '5–20',
    slides: [
      { slide_type: 'percent_split', content: { title: 'Budget 100', prompt: 'Verteile 100 Punkte auf Features', options: [{ id: 'a', text: 'Feature A' }, { id: 'b', text: 'Feature B' }, { id: 'c', text: 'Feature C' }] }, settings: {} },
      { slide_type: 'ranking', content: { title: 'Ranking', prompt: 'Ordne nach Wichtigkeit', options: [{ id: 'a', text: 'Speed' }, { id: 'b', text: 'Qualität' }, { id: 'c', text: 'Kosten' }] }, settings: {} },
    ],
  },
  {
    key: 'academic-seminar',
    category: 'Akademisch & Forschung',
    name: 'Seminar Diskussion',
    desc: 'Verständniskontrolle und Diskussionsanstoß.',
    duration: '20–40 Min.',
    group: '10–80',
    slides: [
      { slide_type: 'number_guess', content: { title: 'Schätzfrage', prompt: 'Schätze den Wert (Zahl)' }, settings: {} },
      { slide_type: 'open', content: { title: 'Diskussion', prompt: 'Welche Frage bleibt offen?' }, settings: { anonymous: true } },
      { slide_type: 'mc_single', content: { title: 'Verständnis', prompt: 'War der Kernpunkt klar?', options: [{ id: 'a', text: 'Ja' }, { id: 'b', text: 'Teilweise' }, { id: 'c', text: 'Nein' }] }, settings: { anonymous: true } },
    ],
  },
];

window.LP_SLIDE_TYPES = [
  { type: 'content', label: 'Inhalt', icon: 'fa-align-left', desc: 'Titel, Text, Bild' },
  { type: 'section', label: 'Kapitel', icon: 'fa-bookmark', desc: 'Trennfolie' },
  { type: 'mc_single', label: 'Multiple Choice', icon: 'fa-circle-dot', desc: 'Eine Antwort' },
  { type: 'mc_multi', label: 'Mehrfachauswahl', icon: 'fa-square-check', desc: 'Mehrere Antworten' },
  { type: 'yesno', label: 'Ja / Nein', icon: 'fa-toggle-on', desc: 'Schnelle Abstimmung' },
  { type: 'wordcloud', label: 'Wortwolke', icon: 'fa-cloud', desc: 'Kurze Begriffe' },
  { type: 'open', label: 'Offene Frage', icon: 'fa-comment', desc: 'Freitext' },
  { type: 'scale', label: 'Skala', icon: 'fa-sliders', desc: 'Bewertung 1–10' },
  { type: 'ranking', label: 'Ranking', icon: 'fa-arrow-down-wide-short', desc: 'Reihenfolge' },
  { type: 'quiz', label: 'Quiz', icon: 'fa-bolt', desc: 'Richtige Antwort + Punkte' },
  { type: 'qa', label: 'Q&A', icon: 'fa-circle-question', desc: 'Fragen & Upvotes' },
  { type: 'brainstorm', label: 'Brainstorming', icon: 'fa-lightbulb', desc: 'Karten sammeln' },
  { type: 'reaction', label: 'Reaktion', icon: 'fa-face-smile', desc: 'Emoji-Feedback' },
  { type: 'number_guess', label: 'Zahl schätzen', icon: 'fa-hashtag', desc: 'Durchschnitt/Median' },
  { type: 'percent_split', label: '100 Punkte', icon: 'fa-chart-pie', desc: 'Prozent verteilen' },
  { type: 'pin_image', label: 'Pin auf Bild', icon: 'fa-location-dot', desc: 'Marker setzen' },
];

window.LP_DEFAULT_CONTENT = {
  content: { title: 'Neue Folie', body: '', imageUrl: '' },
  section: { title: 'Kapitel', subtitle: '' },
  mc_single: { title: 'Frage', prompt: 'Wähle eine Option', options: [{ id: 'a', text: 'Option A' }, { id: 'b', text: 'Option B' }] },
  mc_multi: { title: 'Frage', prompt: 'Wähle mehrere', options: [{ id: 'a', text: 'Option A' }, { id: 'b', text: 'Option B' }], maxSelections: 3 },
  yesno: { title: 'Ja oder Nein?', prompt: '' },
  wordcloud: { title: 'Wortwolke', prompt: 'Gib ein kurzes Wort ein' },
  open: { title: 'Offene Frage', prompt: 'Deine Antwort…' },
  scale: { title: 'Skala', prompt: 'Bewerte von 1 bis 10', min: 1, max: 10, minLabel: 'niedrig', maxLabel: 'hoch' },
  ranking: { title: 'Ranking', prompt: 'Ordne nach Wichtigkeit', options: [{ id: 'a', text: 'A' }, { id: 'b', text: 'B' }, { id: 'c', text: 'C' }] },
  quiz: { title: 'Quiz', prompt: 'Wähle die richtige Antwort', options: [{ id: 'a', text: 'A', correct: false }, { id: 'b', text: 'B', correct: true }] },
  qa: { title: 'Q&A', prompt: 'Stelle deine Frage' },
  brainstorm: { title: 'Brainstorming', prompt: 'Deine Idee…' },
  reaction: { title: 'Reaktion', prompt: 'Wie fühlst du dich?' },
  number_guess: { title: 'Schätzfrage', prompt: 'Gib eine Zahl ein' },
  percent_split: { title: 'Verteile 100 Punkte', prompt: '', options: [{ id: 'a', text: 'A' }, { id: 'b', text: 'B' }] },
  pin_image: { title: 'Pin auf Bild', prompt: 'Tippe auf das Bild', imageUrl: '' },
};

window.LP_DEFAULT_SETTINGS = {
  anonymous: true,
  multipleResponses: false,
  timeLimitSec: 0,
  required: false,
  moderation: false,
  showResultsLive: true,
  profanityFilter: true,
  askName: false,
};
